name: wagtail-content-import CI

on:
  push:
    branches:
      - main
      - master
      - 'stable/**'

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install flake8
        run: |
          python -m pip install flake8
      - name: flake8
        run: |
          flake8 .
      - name: Install isort
        run: |
          python -m pip install isort
      - name: isort
        run: |
          isort .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose up -d
      - name: Run tests
        run: |
          docker-compose exec web ./manage.py test
